### ISSUE TITLE
if i use webpack, how to 

### ISSUE THREAD

**Issue by leadscloud** [odrick/gulp-images-resizer#2]
webpack CopyWebpackPlugin how to config, can you help me ?

**Comment by odrick** [comment]
Describe in more detail, what are you trying to do?
For example: https://pawelgrzybek.com/using-webpack-with-gulpjs/

**Comment by odrick** [comment]
As far as I understand, the problem is solved?)

**Comment by leadscloud** [comment]
@odrick no. i have search all the result by google.   

now i use gulp-images-resizer resize the img.  many webpack plugin is not work.

**Comment by odrick** [comment]
Now you can try this port https://github.com/odrick/webpack-images-resizer
