### ISSUE TITLE
Decimal percentages

### ISSUE THREAD

**Issue by rtalon83** [odrick/gulp-images-resizer#5]
Hi!

Look this example:

I have a image 265x1200, now `gulp-images-resizer` is doing `width = Math.floor(image.bitmap.width * (parseInt(width) / 100))`

What happens when I set a float value? 66.6667%

parseInt(66.6667) -> 66
66 / 100 -> 0.66
265 * 0.66 = 174.9
Math.floor(174.9) -> 174

Correct value: 265 * 66.6667% = 176.66

two/three pixels of difference.

Maybe, will be:

`Math.round(image.bitmap.width * (parseFloat(width) / 100))`
`Math.round(image.bitmap.height * (parseFloat(height) / 100))`

no?

**Comment by rtalon83** [comment]
I make you a pull request with possible solution: 
https://github.com/odrick/gulp-images-resizer/pull/6

**Comment by odrick** [comment]
Yes, this is a correct solution. Merged :)
